### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ZizhengXu** [grapeot/VoiceNoteTaker#3]
Hi, I used the recording button on http://localhost:5000/ to record my voice.
After ending recording, I got these error messages:
```
An error occurred. Please try again. {"readyState":4,"responseText":"<!doctype html>\n<html lang=en>\n  <head>\n    <title>PermissionError: [Errno 13] Permission denied: 'C:\\\\Users\\\\xxxx\\\\AppData\\\\Local\\\\Temp\\\\tmpw6fhik2p.m4a'
Traceback (most recent call last):
  File "VoiceNoteTaker\venv\lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "VoiceNoteTaker\venv\lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "VoiceNoteTaker\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "VoiceNoteTaker\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "VoiceNoteTaker\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "VoiceNoteTaker\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "VoiceNoteTaker\main.py", line 30, in transcribe
    audio_file.save(temp_audio_file.name)
  File "VoiceNoteTaker\venv\lib\site-packages\werkzeug\datastructures.py", line 3002, in save
    dst = open(dst, "wb")
```
tested on Windows 11, venv python version 3.10.10. Does not work using admin Anaconda prompt either.

**Comment by grapeot** [comment]
Looks a Windows privilege issue. I haven't tested it on Windows yet and will get my hands on it this week.

**Comment by grapeot** [comment]
Meanwhile, a quick get around may be, you can try the WSL(2) to run the application.
